# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='licence_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=b'user/image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
    ]
