# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161125_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='licence_image',
            new_name='image',
        ),
    ]
