# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ownername', models.CharField(blank=True, max_length=255, null=True)),
                ('charge_perhour', models.CharField(blank=True, max_length=15, null=True)),
                ('charge_perday', models.CharField(blank=True, max_length=15, null=True)),
                ('charge_perweek', models.CharField(blank=True, max_length=15, null=True)),
                ('i_date', models.IntegerField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, default='y', max_length=1, null=True)),
                ('is_deleted', models.CharField(blank=True, default='n', max_length=1, null=True)),
                ('i_by', models.IntegerField(blank=True, null=True)),
                ('u_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
